### ISSUE TITLE
Amenity search should include `ways` as well

### ISSUE THREAD

**Issue by ramyaragupathy** [oini/poi-finder#1]
@ruthmaben @oini Right now the application looks up only those amenities that are marked as nodes. it'd would be great to include those that are marked as ways as well.

**Comment by ramyaragupathy** [comment]
@oini has this been pushed?

**Comment by oini** [comment]
Yes @ramyaragupathy, here's the [commit](https://github.com/oini/poi-finder/commit/320c26b804c3f255d5c6a9bff7c38354ac24ef9c). Closing the issue here.
